### ISSUE TITLE
BUG in release mode

### ISSUE THREAD

**Issue by sudhanshugairola** [Lucidplus-IT-Solution/device_info_plugin#4]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Serializer for class 'Display' is not found.

**Comment by sudhanshugairola** [comment]
E/flutter ( 8083): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Serializer for class 'Display' is not found.
E/flutter ( 8083): Mark the class as @Serializable or provide the serializer explicitly., null, bd.h: Serializer for class 'Display' is not found.
E/flutter ( 8083): Mark the class as @Serializable or provide the serializer explicitly.
E/flutter ( 8083):      at fd.p0.d(Platform.common.kt:34)
E/flutter ( 8083):      at fd.o0.k(Platform.kt:6)
E/flutter ( 8083):      at bd.k.d(Serializers.kt:23)
E/flutter ( 8083):      at bd.j.b(Unknown Source:1)
E/flutter ( 8083):      at u4.k.onMethodCall(DeviceInfoPlugin.kt:182)
E/flutter ( 8083):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:18)
E/flutter ( 8083):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:19)
E/flutter ( 8083):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:41)
E/flutter ( 8083):      at io.flutter.embedding.engine.dart.DartMessenger.a(DartMessenger.java:1)
E/flutter ( 8083):      at io.flutter.embedding.engine.dart.a.run(R8$$SyntheticClass:13)
E/flutter ( 8083):      at android.os.Handler.handleCallback(Handler.java:942)
E/flutter ( 8083):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 8083):      at android.os.Looper.loopOnce(Looper.java:226)
E/flutter ( 8083):      at android.os.Looper.loop(Looper.java:313)
E/flutter ( 8083):      at android.app.ActivityThread.main(ActivityThread.java:8762)
E/flutter ( 8083):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8083):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/flutter ( 8083):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/flutter ( 8083): )
E/flutter ( 8083): #0      rea.WHd (wmh:652)
E/flutter ( 8083): #1      Aea._rId (zmh:310)
E/flutter ( 8083): <asynchronous suspension>
E/flutter ( 8083): #2      bA.VDe (reh:59)
E/flutter ( 8083): <asynchronous suspension>
E/flutter ( 8083): #3      main (bbh:42)
E/flutter ( 8083): <asynchronous suspension>
E/flutter ( 8083):

**Comment by sudhanshugairola** [comment]
solution
add to proguard

# Keep `Companion` object fields of serializable classes.
# This avoids serializer lookup through `getDeclaredClasses` as done for named companion objects.
-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
   static <1>$Companion Companion;
}

# Keep `serializer()` on companion objects (both default and named) of serializable classes.
-if @kotlinx.serialization.Serializable class ** {
   static **$* *;
}
-keepclassmembers class <2>$<3> {
   kotlinx.serialization.KSerializer serializer(...);
}

# Keep `INSTANCE.serializer()` of serializable objects.
-if @kotlinx.serialization.Serializable class ** {
   public static ** INSTANCE;
}
-keepclassmembers class <1> {
   public static <1> INSTANCE;
   kotlinx.serialization.KSerializer serializer(...);
}

# @Serializable and @Polymorphic are used at runtime for polymorphic serialization.
-keepattributes RuntimeVisibleAnnotations,AnnotationDefault
